### ISSUE TITLE
Mimics and other enemies don't speak ( Mirage v1.10.0 )

### ISSUE THREAD

**Issue by Hang0BTW** [qwbarch/mirage#90] opened 2024-10-04 03:46 UTC
I am change config in config editor cause in game you cant change, but nothing, no one can speak my or friend's voice

**Comment by qwbarch** [comment] 2024-10-07 01:11
Are recordings being created? I have a report of this on discord and I'm trying to figure out the cause

**Comment by qwbarch** [comment] 2024-10-11 15:17
Should be fixed in the latest update. If the issue still occurs, feel free to re-open the issue

**Closed by qwbarch** 2024-10-11 15:17 UTC
