### ISSUE TITLE
I think voice is still recording even i didn't press the push to talk button

### ISSUE THREAD

**Issue by habacksill** [qwbarch/mirage#107] opened 2024-11-20 08:37 UTC
I didn't press the push to talk button, but The monster is still mimicing my sounds.
Does monsters can mimic my game sound?
I can also hear my gamesounds(ex, ships landing sounds)

**Comment by qwbarch** [comment] 2024-11-23 02:08
Is this on ``v1.12.2``? This issue should already be fixed in the latest version.  
As for whether monsters can mimic game sounds, the answer is no. They only mimic what you say via your microphone.

**Comment by habacksill** [comment] 2024-11-23 12:45
Well, Actually I didn't connect the microphone, just a speaker only. is this the reason?
and version was latest version.

**Comment by qwbarch** [comment] 2024-11-23 17:13
Well in that case your speakers are probably just recording the game sounds off of itself then?
Regarding it recording things where you haven't pressed push to talk, do you happen to have ``Never Delete Recordings`` enabled on LethalSettings? This was a bug in ``1.12.1`` that should've been fixed in ``1.12.2``.

**Comment by habacksill** [comment] 2024-11-24 04:32
![스크린샷(87)](https://github.com/user-attachments/assets/c9726878-aea5-4424-87b4-bb7ed954973d)
you mean this? I didn't change this settings at all, except a mirage settings about masked enemy

**Comment by qwbarch** [comment] 2024-11-24 05:44
Hmm weird. I'm not really sure what the issue is for now then, since it works on my end. I'll leave this issue open and hopefully I can get more clues from others that are having the same issue

**Comment by habacksill** [comment] 2024-11-25 08:24
Well I found something that the monsters actually mimicing my monitor background sounds
not my microphone voice. (ex, Youtube video sounds)

**Comment by qwbarch** [comment] 2024-11-25 18:01
Sounds like for whatever reason, dissonance (the voice chat system LC uses) is providing me the wrong microphone data.  
I don't have the option to pick which microphone to use though, so this isn't something I can fix

**Closed** 2024-11-26 13:31 UTC
