### ISSUE TITLE
Error occurred while mimicking voice: NAudio.MmException: AcmNotPossible calling acmFormatSuggest

### ISSUE THREAD

**Issue by 1srm** [qwbarch/mirage#95] opened 2024-10-19 14:32 UTC
Hello, my friend has this error. What he should to do with it? He is only one who has this error

[Error  :qwbarch.Mirage] Error occurred while mimicking voice: NAudio.MmException: AcmNotPossible calling acmFormatSuggest
  at NAudio.MmException.Try (NAudio.MmResult result, System.String function) [0x0000a] in <1de6b66de24a4618bd8723db1cfe545d>:0
  at NAudio.Wave.Compression.AcmStream.SuggestPcmFormat (NAudio.Wave.WaveFormat compressedFormat) [0x0003f] in <f178471da6cb4e6b9dbad166e9b46bdd>:0
  at NAudio.Wave.AcmMp3FrameDecompressor..ctor (NAudio.Wave.WaveFormat sourceFormat) [0x00006] in <f178471da6cb4e6b9dbad166e9b46bdd>:0
  at Mirage.Domain.Audio.Receiver.AudioReceiver (UnityEngine.AudioSource audioSource, Mirage.Domain.Audio.Frame+PcmHeader pcmHeader, Microsoft.FSharp.Core.FSharpFunc2[T,TResult] onFrameDecompressed) [0x00069] in .\Mirage\Domain\Audio\Receiver.fs:52
  at Mirage.Unity.AudioStream+clo@63.Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00029] in .\Mirage\Unity\AudioStream.fs:65
  at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult] (Microsoft.FSharp.Control.AsyncActivation1[T] ctxt, TResult result1, Microsoft.FSharp.Core.FSharpFunc2[T,TResult] part2) [0x00005] in D:\a\_work\1\s\src\FSharp.Core\async.fs:510
  at Mirage.Unity.AudioStream+StreamAudioFromFile@109-4.Invoke (Microsoft.FSharp.Control.AsyncActivation1[T] ctxt) [0x00000] in <e3e3163e79312fd2863cf9cbc3c9d161>:0
  at Microsoft.FSharp.Control.Trampoline.Execute (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] firstAction) [0x00017] in D:\a_work\1\s\src\FSharp.Core\async.fs:112

**Comment by qwbarch** [comment] 2024-10-22 01:34
Sorry for the late response. Can you ask him for a full log?

**Comment by 1srm** [comment] 2024-10-23 15:21
Full log you mean with starting game? If it is, I checked it. He had only this error. But two days ago we are tried to start mirage + skinwalkers and got this. A new error.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Mirage.Unity.AudioStream+AudioStream.SendFrameClientRpc (Mirage.Domain.Audio.Frame+FrameData frameData) (at ./Mirage/Unity/AudioStream.fs:148)
Mirage.Unity.AudioStream+AudioStream.rpc_handler_249455753 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.RpcParams rpcParams) (at <e3e3163e79312fd2863cf9cbc3c9d161>:IL_0049)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkMessageManager:ReceiveMessage(FastBufferReader, NetworkContext&, NetworkMessageManager)
Unity.Netcode.NetworkMessageManager:HandleMessage(NetworkMessageHeader&, FastBufferReader, UInt64, Single, Int32)
Unity.Netcode.NetworkMessageManager:ProcessIncomingMessageQueue()
Unity.Netcode.NetworkManager:NetworkUpdate(NetworkUpdateStage)
Unity.Netcode.NetworkUpdateLoop:RunNetworkUpdateStage(NetworkUpdateStage)
Unity.Netcode.<>c:<CreateLoopSystem>b__0_0()

I know that mirage its not compatible with skinwalkers, but we wanted to play with our voices

**Comment by qwbarch** [comment] 2024-10-24 00:25
Hm could you drop your profile code? I'll try to take a look when I have time.

**Comment by 1srm** [comment] 2024-11-09 12:41
My friend has now two errors:

[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <787acc3c9a4c471ba7d971300105af24>:0)
EnemyVent.SyncVentSpawnTimeClientRpc (System.Int32 time, System.Int32 enemyIndex) (at <d491ed1d4cc34874a2498af41192fe04>:0)
EnemyVent.rpc_handler_3841281693 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.RpcParams rpcParams) (at <d491ed1d4cc34874a2498af41192fe04>:0)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkMessageManager:ReceiveMessage(FastBufferReader, NetworkContext&, NetworkMessageManager)
Unity.Netcode.NetworkMessageManager:HandleMessage(NetworkMessageHeader&, FastBufferReader, UInt64, Single, Int32)
Unity.Netcode.NetworkMessageManager:ProcessIncomingMessageQueue()
Unity.Netcode.NetworkManager:NetworkUpdate(NetworkUpdateStage)
Unity.Netcode.NetworkUpdateLoop:RunNetworkUpdateStage(NetworkUpdateStage)
Unity.Netcode.<>c:<CreateLoopSystem>b__0_0()

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Mirage.Unity.AudioStream+AudioStream.SendFrameClientRpc (Mirage.Domain.Audio.Frame+FrameData frameData) (at ./Mirage/Unity/AudioStream.fs:151)
Mirage.Unity.AudioStream+AudioStream.rpc_handler_249455753 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.RpcParams rpcParams) (at <cf26d462f10398a7d048dd2c87e69add>:0)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.RpcParams& rpcParams) (at <895801699cfc4b4ab52267f31e2a4998>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, RpcParams&)
Unity.Netcode.ClientRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkMessageManager:ReceiveMessage(FastBufferReader, NetworkContext&, NetworkMessageManager)
Unity.Netcode.NetworkMessageManager:HandleMessage(NetworkMessageHeader&, FastBufferReader, UInt64, Single, Int32)
Unity.Netcode.NetworkMessageManager:ProcessIncomingMessageQueue()
Unity.Netcode.NetworkManager:NetworkUpdate(NetworkUpdateStage)
Unity.Netcode.NetworkUpdateLoop:RunNetworkUpdateStage(NetworkUpdateStage)
Unity.Netcode.<>c:<CreateLoopSystem>b__0_0()

Our code were 019310f0-6aee-b1cf-b9e2-6b83cab8f051 but it's clean mirage

**Comment by qwbarch** [comment] 2024-11-12 04:57
Sorry for the late response and thanks for reporting the additional error. Honestly this might be difficult for me to track down since this error never happens for me on a clean installation with just Mirage

**Comment by qwbarch** [comment] 2024-11-12 07:33
Do you know what OS your friends runs on? Is it Windows 10/11?
Can you also ask your friend to check Mirage's audio folder? Inside the Lethal Company folder, there should be one called ``Mirage`` and then ``Recording``.
See what recordings there are, and see if they can be played manually, just to check if it's valid audio or not

**Comment by 1srm** [comment] 2024-11-12 16:06
Its very strange. Because we played with skinwalkers and he could hear the voices. Mirage and Skinwalkers have same audio format. I wanted change windows to test, maybe really windows 11 is invalid version to mirage

**Comment by qwbarch** [comment] 2024-11-12 16:34
Windows 11 is fine, I use that as well. I'll try something out push it to the experimental build, hopefully will be ready within a day

**Comment by qwbarch** [comment] 2024-11-12 22:44
@1srm Can you and your friends try using [MirageExperimental 0.0.44](<https://thunderstore.io/c/lethal-company/p/qwbarch/MirageExperimental/>) and let me know if the issue is fixed? FYI the mod is marked as deprecated to hide it from the search bar, don't worry about it being deprecated. Make sure the original ``Mirage`` is removed from your profile as well when running ``MirageExperimental``

**Comment by 1srm** [comment] 2024-11-15 19:57
0.0.45 is good version, it works. But mirage 1.11.2 is not working

**Comment by 1srm** [comment] 2024-11-15 20:29
Can you add this fix on Content Warning Mirage too, when you done with Lethal Company Mirage?

**Comment by qwbarch** [comment] 2024-11-15 20:32
Content Warning's version is completely broken and I don't have time to work on it sadly

**Comment by qwbarch** [comment] 2024-11-15 22:48
Fixed in ``Mirage v1.12.0``. Thanks for the bug report and for testing

**Closed by qwbarch** 2024-11-15 22:48 UTC
