### ISSUE TITLE
All enemies use the same (Masked?) voice delays (v1.11.1 Lethal Company)

### ISSUE THREAD

**Issue by SgtNailer** [qwbarch/mirage#99] opened 2024-10-28 14:59 UTC
Tested with only me on the server and only Mirage v1.11.1 (and its dependencies) enabled on Lethal Company.

Using the config files I have tried to give masked and non-masked enemies different minimum and maximum delays for their voice playbacks. However when testing, non-masked enemies are seemingly using the delays specified for masked when mimicking my voice. They are clearly not using the delays specified for non-masked enemies in the cfg file at least.

I assume this is a bug introduced with the newer versions as different delays still work on the old version 1.8.2.

**Comment by qwbarch** [comment] 2024-10-30 03:12
Is this relating to the issue where voices seem to repeat? I'm currently working on trying to fix that bug, but I haven't been able to reproduce it once so it's a bit hard to figure out a fix

**Comment by SgtNailer** [comment] 2024-10-30 12:52
Hmmm I'm not 100% sure but I don't think so because the voice-playbacks were seemingly not repeating. They were simply using much shorter delays between playback rates than I had specified in the config for non-masked enemies. It was quite easy to test and reproduce. 

So unless the issue where voices seem to repeat also makes the voices playback much more often then I don't think it's related.

**Comment by SheriffSans** [comment] 2024-11-01 11:47
The same problem. NON-masked enemies use masked delay values. It looks like there is some kind of error in the code.

**Comment by SheriffSans** [comment] 2024-11-06 15:47
@qwbarch Any idea where the problem is?

**Comment by qwbarch** [comment] 2024-11-12 04:57
@SheriffSans Hey, sorry for the really late response. I've been busy lately and haven't had the time to look at GitHub.
I'll see if I can look into this problem sometime this week, but no promises, it just depends on when I'm free

**Comment by qwbarch** [comment] 2024-11-12 06:40
Fixed in ``v1.11.2``. Sorry again for the super late response.

**Closed by qwbarch** 2024-11-12 06:40 UTC

**Comment by SgtNailer** [comment] 2024-11-12 15:27
Hey no worries! I'm ever thankful for modders releasing cool stuff for free! Thanks for fixing the issue!
