### ISSUE TITLE
Adding custom audio deletes the folder upon boot

### ISSUE THREAD

**Issue by 404cofee** [qwbarch/mirage#98] opened 2024-10-23 12:43 UTC
I have been adding audio to the folder in the mirage recordings folder directory these are either modified clips that the mod created that have a glitchy noise that I manually removed or prerecorded lines.

I do not know if this is some sort of measure or what but to me I find it hindering and to me it doesn't make sense that it is part of it so I am assuming that it is a glitch.

**Comment by qwbarch** [comment] 2024-10-24 00:25
That's intended. The folder is deleted on start/close to avoid filling up the user's disk space.  
You can optionally choose to never have the folder deleted by enabling the ``Never delete recordings`` option in ``LethalSettings``.

**Comment by 404cofee** [comment] 2024-10-24 12:47
> That's intended. The folder is deleted on start/close to avoid filling up the user's disk space. You can optionally choose to never have the folder deleted by enabling the `Never delete recordings` option in `LethalSettings`.

ok I then this is not closed I had that on, I just put my own audio in and it deletes the entire folder despite having it on.

**Comment by 404cofee** [comment] 2024-10-25 17:40
I put this on my other comment but I will put it here just in case
https://github.com/user-attachments/assets/70e01d52-9295-4446-b083-d6cc5a642da8

**Comment by qwbarch** [comment] 2024-10-26 05:00
``Never delete recordings`` option works perfectly fine for me. When I have it enabled, my recordings are still there

**Comment by 404cofee** [comment] 2024-10-26 11:42
> `Never delete recordings` option works perfectly fine for me. When I have it enabled, my recordings are still there

in the comment before the one with the video I said have the option on and I do have it on, I do not know why it is happening man.

**Comment by qwbarch** [comment] 2024-10-30 03:13
I mean there's not much I can do about that, the option works for me and when I asked someone else to test it, it works for them as well

**Comment by qwbarch** [comment] 2024-10-30 03:14
I'm not sure if maybe LethalSettings is unable to edit the ``settings.json`` properly. Can you double check its contents and post it here?

**Comment by 404cofee** [comment] 2024-11-06 17:22
This is the settings sorry for being late on this I just forgot about it
{"localPlayerVolume":0.2,"neverDeleteRecordings":true}

**Comment by qwbarch** [comment] 2024-11-12 05:07
Sorry for the late response as well, haven't had the time to look at GitHub recently.

That's odd though, that shows it internally set it properly, yet it's still ignoring the settings somehow.
Honestly I don't know what I can do to fix it as that never happens to me, but I'll leave this issue open as maybe others with the same issue can comment here

**Comment by qwbarch** [comment] 2024-11-15 06:02
Out of curiosity, does your file path contain any non-ascii characters? E.g. from your windows username? I'm wondering if the issue is with it not being able to load the file properly due to whatever reason

**Comment by 404cofee** [comment] 2024-11-21 16:38
Apologies for my late response chap, There is no non-ascii characters in any of the files or anything that leads to any of those paths on my computer.

**Comment by qwbarch** [comment] 2024-11-23 01:52
I'm afraid I have no leads then. I'll leave this issue opened but I don't have any ideas on what the issue is as of now

**Comment by qwbarch** [comment] 2024-12-08 21:22
It turns out the issue is that I didn't make my code wait for the settings to finish loading first.

The reason it worked properly for me is because it ran like this:
- Load settings in the background
- Settings finished loading quickly enough
- Delete recording reads the settings, which loaded fine

The reason it didn't work properly for you is because it ran like this:
- Load settings in the background
- Attempts to read settings to delete recordings, and because the settings hasn't loaded yet, it reads the default value (which is to delete the recordings)

This is fixed in the experimental build, and will be part of the official build soon.  
I've also included a setting to disallow recording new audio clips, for cases like this where players just want to include their own clips and not use anything else.

**Comment by qwbarch** [comment] 2024-12-09 21:56
Fixed in ``v1.13.0``, thanks for the report and sorry for taking so long to fix it

**Closed by qwbarch** 2024-12-09 21:56 UTC
