### ISSUE TITLE
Mirage mod doesn't work ( Content Warning)

### ISSUE THREAD

**Issue by kayabster** [qwbarch/mirage#72] opened 2024-06-24 21:50 UTC
Hello, I downloaded everything I needed, but the mod doesn’t work, the mobs are silent and don’t say anything. I have many error like 
Error  :qwbarch.Mirage] AudioStream#SendFrameClientRpc was called while AudioReceiver has not been initialized yet.

**Comment by qwbarch** [comment] 2024-06-25 01:52
An update must've screwed up the mod. I don't have any time to look into this right now though sadly

**Comment by kayabster** [comment] 2024-06-25 10:07
the mod works for my friends, I understand you, thank you!

**Comment by qwbarch** [comment] 2024-06-25 23:51
Ah if it works for your friends I have a feeling it's because of one of the dependencies. This was fixed in the Lethal Company version by updating one of the dependencies (on my side). I'll put an update for BarchLib on Content Warning that hopefully fixes this issue

**Comment by qwbarch** [comment] 2024-06-26 02:35
I've pushed out an update for BarchLib that should fix this issue. Let me know if that fixes it for you

**Comment by kayabster** [comment] 2024-06-26 11:53
Hello, when I play solo, everyone is silent and there are no errors in the console, but when I play with friends, I constantly get the errors that I described in my first request. Is there something wrong with my computer? I really don’t understand what the problem is.

**Comment by qwbarch** [comment] 2024-06-26 20:36
This is with the updated BarchLib? I'm not sure what the problem is then, sorry

**Comment by kayabster** [comment] 2024-06-26 20:47
yes, I updated BarchLig. ok, thanks for taking the time to do this.

**Comment by qwbarch** [comment] 2024-07-04 03:23
@MeowUzbek I'm not sure what was changed for Mirage to break, but it seems to not be working properly based on all the reports I've been receiving. Unfortunately I don't have time to look into it at the moment, but I'll look into it in the future when I have time

**Comment by qwbarch** [comment] 2024-10-01 01:02
No time to support the content warning mod anymore, closing this issue

**Closed by qwbarch** 2024-10-01 01:02 UTC
Labels: game:content-warning
